In [108]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [109]:
train_df=pd.read_csv(r"C:\Users\hp\Downloads\3.Chapter_ML_datas\ML_Projects\1.Mercedes-Benz Greener Manufacturing\train.csv")

In [110]:
train_df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [111]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB

In [112]:
train_df.shape

(4209, 378)

In [113]:
#Extract the target variable
y=train_df['y']

In [114]:
test_df=pd.read_csv(r"C:\Users\hp\Downloads\3.Chapter_ML_datas\ML_Projects\1.Mercedes-Benz Greener Manufacturing\test.csv")

In [115]:
test_df.shape

(4209, 377)

In [116]:
#1.If for any column(s), the variance is equal to zero, then you need to remove those variable(s)

var1=train_df.var(axis=0) #Checking the variance of train dataset
var1

ID      5.941936e+06
y       1.607667e+02
X10     1.313092e-02
X11     0.000000e+00
X12     6.945713e-02
            ...
X380    8.014579e-03
X382    7.546747e-03
X383    1.660732e-03
X384    4.750593e-04
X385    1.423823e-03
Length: 370, dtype: float64

In [117]:
#Obtain the index of all the columns that has zero variance
list1=[]
for i,j in var1.items():
    if j==0:
        list1.append(i)
list1

['X11',
 'X93',
 'X107',
 'X233',
 'X235',
 'X268',
 'X289',
 'X290',
 'X293',
 'X297',
 'X330',
 'X347']

In [118]:
#Drop all the columns that has zero variance
train_df=train_df.drop(columns=list1,axis=1)
train_df.shape

(4209, 366)

In [119]:
# #Checking the variance of test dataset
var2=test_df.var(axis=0)
var2

ID      5.871311e+06
X10     1.865006e-02
X11     2.375861e-04
X12     6.885074e-02
X13     5.734498e-02
            ...
X380    8.014579e-03
X382    8.715481e-03
X383    4.750593e-04
X384    7.124196e-04
X385    1.660732e-03
Length: 369, dtype: float64

In [120]:
list2=[]
for i,j in var2.items():
    if j==0:
        list2.append(i)
list2

['X257', 'X258', 'X295', 'X296', 'X369']

In [121]:
test_df=test_df.drop(columns=list2,axis=1)
test_df.shape

(4209, 372)

In [122]:
#2.Check for null and unique values for test and train sets.
train_df.isnull().sum()

ID      0
y       0
X0      0
X1      0
X2      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 366, dtype: int64

In [123]:
train_missing_val=0
for col in train_df.columns:
    for item in train_df[col].isnull():
        if item==True:
            train_missing_val+=1
train_missing_val

0

In [124]:
#Check whether there is any missing values in test dataset
test_missing_val=0
for col in test_df.columns:
    for item in test_df[col].isnull():
        if item==True:
            test_missing_val+=1
test_missing_val

0

In [125]:
#3.Apply label encoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [126]:
#checking for the unique columns in the dataset
for col in train_df.columns:
    print(col,train_df[col].nunique())

ID 4209
y 2545
X0 47
X1 27
X2 44
X3 7
X4 4
X5 29
X6 12
X8 25
X10 2
X12 2
X13 2
X14 2
X15 2
X16 2
X17 2
X18 2
X19 2
X20 2
X21 2
X22 2
X23 2
X24 2
X26 2
X27 2
X28 2
X29 2
X30 2
X31 2
X32 2
X33 2
X34 2
X35 2
X36 2
X37 2
X38 2
X39 2
X40 2
X41 2
X42 2
X43 2
X44 2
X45 2
X46 2
X47 2
X48 2
X49 2
X50 2
X51 2
X52 2
X53 2
X54 2
X55 2
X56 2
X57 2
X58 2
X59 2
X60 2
X61 2
X62 2
X63 2
X64 2
X65 2
X66 2
X67 2
X68 2
X69 2
X70 2
X71 2
X73 2
X74 2
X75 2
X76 2
X77 2
X78 2
X79 2
X80 2
X81 2
X82 2
X83 2
X84 2
X85 2
X86 2
X87 2
X88 2
X89 2
X90 2
X91 2
X92 2
X94 2
X95 2
X96 2
X97 2
X98 2
X99 2
X100 2
X101 2
X102 2
X103 2
X104 2
X105 2
X106 2
X108 2
X109 2
X110 2
X111 2
X112 2
X113 2
X114 2
X115 2
X116 2
X117 2
X118 2
X119 2
X120 2
X122 2
X123 2
X124 2
X125 2
X126 2
X127 2
X128 2
X129 2
X130 2
X131 2
X132 2
X133 2
X134 2
X135 2
X136 2
X137 2
X138 2
X139 2
X140 2
X141 2
X142 2
X143 2
X144 2
X145 2
X146 2
X147 2
X148 2
X150 2
X151 2
X152 2
X153 2
X154 2
X155 2
X156 2
X157 2
X158 2
X159 2
X160 2
X161 2
X162 2
X163 2
X164 2
X165 2
X166 2
X167 2
X168 2
X169 2
X170 2
X171 2
X172 2
X173 2
X174 2
X175 2
X176 2
X177 2
X178 2
X179 2
X180 2
X181 2
X182 2
X183 2
X184 2
X185 2
X186 2
X187 2
X189 2
X190 2
X191 2
X192 2
X194 2
X195 2
X196 2
X197 2
X198 2
X199 2
X200 2
X201 2
X202 2
X203 2
X204 2
X205 2
X206 2
X207 2
X208 2
X209 2
X210 2
X211 2
X212 2
X213 2
X214 2
X215 2
X216 2
X217 2
X218 2
X219 2
X220 2
X221 2
X222 2
X223 2
X224 2
X225 2
X226 2
X227 2
X228 2
X229 2
X230 2
X231 2
X232 2
X234 2
X236 2
X237 2
X238 2
X239 2
X240 2
X241 2
X242 2
X243 2
X244 2
X245 2
X246 2
X247 2
X248 2
X249 2
X250 2
X251 2
X252 2
X253 2
X254 2
X255 2
X256 2
X257 2
X258 2
X259 2
X260 2
X261 2
X262 2
X263 2
X264 2
X265 2
X266 2
X267 2
X269 2
X270 2
X271 2
X272 2
X273 2
X274 2
X275 2
X276 2
X277 2
X278 2
X279 2
X280 2
X281 2
X282 2
X283 2
X284 2
X285 2
X286 2
X287 2
X288 2
X291 2
X292 2
X294 2
X295 2
X296 2
X298 2
X299 2
X300 2
X301 2
X302 2
X304 2
X305 2
X306 2
X307 2
X308 2
X309 2
X310 2
X311 2
X312 2
X313 2
X314 2
X315 2
X316 2
X317 2
X318 2
X319 2
X320 2
X321 2
X322 2
X323 2
X324 2
X325 2
X326 2
X327 2
X328 2
X329 2
X331 2
X332 2
X333 2
X334 2
X335 2
X336 2
X337 2
X338 2
X339 2
X340 2
X341 2
X342 2
X343 2
X344 2
X345 2
X346 2
X348 2
X349 2
X350 2
X351 2
X352 2
X353 2
X354 2
X355 2
X356 2
X357 2
X358 2
X359 2
X360 2
X361 2
X362 2
X363 2
X364 2
X365 2
X366 2
X367 2
X368 2
X369 2
X370 2
X371 2
X372 2
X373 2
X374 2
X375 2
X376 2
X377 2
X378 2
X379 2
X380 2
X382 2
X383 2
X384 2
X385 2

In [127]:
#Since only the first 10 columns have more number of unique values, apply label encoder from X0 to X8
X= train_df[['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8']].apply(le.fit_transform)

In [128]:
X.head()

   X0  X1  X2  X3  X4  X5  X6  X8
0  32  23  17   0   3  24   9  14
1  32  21  19   4   3  28  11  14
2  20  24  34   2   3  27   9  23
3  20  21  34   5   3  27  11   4
4  20  23  34   5   3  12   3  13

In [129]:
X.shape,y.shape

((4209, 8), (4209,))

In [130]:
#applying the label encoder to the test dataset as well
for col in test_df.columns:
    print(col,test_df[col].nunique())

ID 4209
X0 49
X1 27
X2 45
X3 7
X4 4
X5 32
X6 12
X8 25
X10 2
X11 2
X12 2
X13 2
X14 2
X15 2
X16 2
X17 2
X18 2
X19 2
X20 2
X21 2
X22 2
X23 2
X24 2
X26 2
X27 2
X28 2
X29 2
X30 2
X31 2
X32 2
X33 2
X34 2
X35 2
X36 2
X37 2
X38 2
X39 2
X40 2
X41 2
X42 2
X43 2
X44 2
X45 2
X46 2
X47 2
X48 2
X49 2
X50 2
X51 2
X52 2
X53 2
X54 2
X55 2
X56 2
X57 2
X58 2
X59 2
X60 2
X61 2
X62 2
X63 2
X64 2
X65 2
X66 2
X67 2
X68 2
X69 2
X70 2
X71 2
X73 2
X74 2
X75 2
X76 2
X77 2
X78 2
X79 2
X80 2
X81 2
X82 2
X83 2
X84 2
X85 2
X86 2
X87 2
X88 2
X89 2
X90 2
X91 2
X92 2
X93 2
X94 2
X95 2
X96 2
X97 2
X98 2
X99 2
X100 2
X101 2
X102 2
X103 2
X104 2
X105 2
X106 2
X107 2
X108 2
X109 2
X110 2
X111 2
X112 2
X113 2
X114 2
X115 2
X116 2
X117 2
X118 2
X119 2
X120 2
X122 2
X123 2
X124 2
X125 2
X126 2
X127 2
X128 2
X129 2
X130 2
X131 2
X132 2
X133 2
X134 2
X135 2
X136 2
X137 2
X138 2
X139 2
X140 2
X141 2
X142 2
X143 2
X144 2
X145 2
X146 2
X147 2
X148 2
X150 2
X151 2
X152 2
X153 2
X154 2
X155 2
X156 2
X157 2
X158 2
X159 2
X160 2
X161 2
X162 2
X163 2
X164 2
X165 2
X166 2
X167 2
X168 2
X169 2
X170 2
X171 2
X172 2
X173 2
X174 2
X175 2
X176 2
X177 2
X178 2
X179 2
X180 2
X181 2
X182 2
X183 2
X184 2
X185 2
X186 2
X187 2
X189 2
X190 2
X191 2
X192 2
X194 2
X195 2
X196 2
X197 2
X198 2
X199 2
X200 2
X201 2
X202 2
X203 2
X204 2
X205 2
X206 2
X207 2
X208 2
X209 2
X210 2
X211 2
X212 2
X213 2
X214 2
X215 2
X216 2
X217 2
X218 2
X219 2
X220 2
X221 2
X222 2
X223 2
X224 2
X225 2
X226 2
X227 2
X228 2
X229 2
X230 2
X231 2
X232 2
X233 2
X234 2
X235 2
X236 2
X237 2
X238 2
X239 2
X240 2
X241 2
X242 2
X243 2
X244 2
X245 2
X246 2
X247 2
X248 2
X249 2
X250 2
X251 2
X252 2
X253 2
X254 2
X255 2
X256 2
X259 2
X260 2
X261 2
X262 2
X263 2
X264 2
X265 2
X266 2
X267 2
X268 2
X269 2
X270 2
X271 2
X272 2
X273 2
X274 2
X275 2
X276 2
X277 2
X278 2
X279 2
X280 2
X281 2
X282 2
X283 2
X284 2
X285 2
X286 2
X287 2
X288 2
X289 2
X290 2
X291 2
X292 2
X293 2
X294 2
X297 2
X298 2
X299 2
X300 2
X301 2
X302 2
X304 2
X305 2
X306 2
X307 2
X308 2
X309 2
X310 2
X311 2
X312 2
X313 2
X314 2
X315 2
X316 2
X317 2
X318 2
X319 2
X320 2
X321 2
X322 2
X323 2
X324 2
X325 2
X326 2
X327 2
X328 2
X329 2
X330 2
X331 2
X332 2
X333 2
X334 2
X335 2
X336 2
X337 2
X338 2
X339 2
X340 2
X341 2
X342 2
X343 2
X344 2
X345 2
X346 2
X347 2
X348 2
X349 2
X350 2
X351 2
X352 2
X353 2
X354 2
X355 2
X356 2
X357 2
X358 2
X359 2
X360 2
X361 2
X362 2
X363 2
X364 2
X365 2
X366 2
X367 2
X368 2
X370 2
X371 2
X372 2
X373 2
X374 2
X375 2
X376 2
X377 2
X378 2
X379 2
X380 2
X382 2
X383 2
X384 2
X385 2

In [131]:
#Apply Label Encoder on the test data
test_df = test_df[['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8']].apply(le.fit_transform)

In [132]:
test_df.head()

   X0  X1  X2  X3  X4  X5  X6  X8
0  21  23  34   5   3  26   0  22
1  42   3   8   0   3   9   6  24
2  21  23  17   5   3   0   9   9
3  21  13  34   5   3  31  11  13
4  45  20  17   2   3  30   8  12

In [133]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2,random_state=1)

In [134]:
xtrain.shape,ytrain.shape,xtest.shape,ytest.shape

((3367, 8), (3367,), (842, 8), (842,))

In [135]:
#4.Perform dimensionality reduction.
from sklearn.decomposition import PCA
pca=PCA(n_components=0.95)

In [136]:
pca.fit(xtrain)

PCA(n_components=0.95)

In [137]:
xtrain_pca=pca.transform(xtrain)

In [138]:
xtrain_pca.shape

(3367, 5)

In [139]:
xtest_pca=pca.transform(xtest)

In [140]:
xtest_pca.shape

(842, 5)

In [141]:
#5.Predict your test_df values using XGBoost.
from xgboost import XGBRegressor
xgb=XGBRegressor()

In [142]:
xgb.fit(xtrain_pca,ytrain)
y_pred=xgb.predict(xtest_pca)
y_pred

array([ 96.774055, 108.397606, 113.43816 , 102.92601 ,  74.92526 ,
        90.805885,  91.63885 ,  93.50609 ,  90.79651 , 111.54865 ,
        93.23259 , 102.75917 ,  97.101616,  94.40552 , 104.13975 ,
       100.39677 , 110.40406 , 101.28798 ,  95.04786 , 109.410706,
       110.388664, 114.14016 , 108.853615,  92.94185 , 100.63025 ,
       111.72815 ,  92.96333 , 109.188644,  93.41996 ,  97.04756 ,
       109.2221  , 113.8912  ,  96.46233 , 108.612045, 104.2229  ,
        89.69772 ,  95.56084 ,  96.71266 , 103.08099 , 109.97501 ,
       125.57242 , 114.341095, 102.94612 ,  99.88307 ,  91.71425 ,
       108.835014,  97.5979  , 103.41831 , 101.734634, 102.746925,
        88.95947 , 109.38394 ,  75.72965 ,  94.863754, 106.21291 ,
       104.73322 ,  90.28327 , 101.82412 , 106.38424 , 100.19796 ,
        93.13841 ,  93.45231 ,  96.747086, 105.359764,  93.05446 ,
        93.09014 ,  94.19353 , 114.54126 ,  96.21562 ,  93.51823 ,
       105.161064,  93.80637 ,  94.19171 ,  94.073   , 109.52913 ,
       100.94648 , 104.09055 , 106.73921 , 108.48598 ,  99.290886,
        96.91477 ,  98.65999 , 107.33972 ,  92.509636, 101.193054,
       114.72552 ,  99.23282 , 102.61146 , 111.46372 , 107.288414,
       110.85865 , 114.119896, 111.200966,  94.40552 ,  96.67365 ,
       110.30067 ,  99.802635,  97.76883 ,  96.36696 ,  94.58385 ,
       100.99453 , 104.48656 ,  99.81677 , 102.90194 ,  93.57099 ,
       104.67255 ,  91.25013 ,  93.54508 , 109.789085,  95.877655,
        91.11271 , 111.500015, 114.54126 , 116.911644,  99.01662 ,
        98.37855 ,  96.745384, 112.17134 ,  91.88925 ,  77.43554 ,
       101.14713 ,  91.45208 ,  98.820946,  94.09956 , 106.73921 ,
        99.07969 , 110.79736 ,  96.57947 ,  99.84723 ,  98.555466,
       100.42313 ,  91.66149 , 111.2633  , 110.35046 ,  90.75881 ,
       110.10403 ,  98.531   ,  93.52294 , 117.68614 , 101.43494 ,
       107.17923 , 107.65207 , 106.23665 , 111.24786 ,  91.21201 ,
        95.67583 , 107.91092 , 102.10125 , 113.98391 , 109.53948 ,
        92.2117  , 133.49976 , 108.17013 , 116.62243 ,  93.95999 ,
        95.00835 ,  94.69857 , 106.160385, 103.72253 , 106.73921 ,
        84.3154  ,  90.9192  ,  88.931496, 100.86442 ,  96.64495 ,
        96.73552 , 102.020004, 102.97268 ,  96.23622 , 103.35315 ,
       107.65287 ,  96.550545,  96.91642 ,  87.54495 , 104.33683 ,
        92.059525, 108.10543 ,  99.09643 , 110.86753 , 101.4192  ,
        92.996704,  79.66337 , 103.58594 ,  99.910545, 104.82603 ,
       106.3965  ,  95.31201 ,  96.310776, 101.83673 , 103.94179 ,
       106.15496 ,  92.38023 , 100.42129 ,  97.97037 ,  94.627426,
       105.80543 , 103.846275,  79.195694,  89.83769 ,  91.73233 ,
       105.93844 , 117.208954, 102.62304 ,  99.73816 , 109.06726 ,
       113.44863 , 112.780174,  91.205956, 109.82801 ,  95.607   ,
        92.20731 , 110.227905,  96.74616 , 107.15873 ,  98.29795 ,
       105.86574 , 107.97284 , 101.02384 ,  95.04052 ,  92.83448 ,
       109.85238 , 111.637184, 110.37338 ,  99.90314 ,  90.982506,
       106.135765, 101.07938 , 118.62954 ,  96.786156, 115.57582 ,
        96.116585,  91.27403 , 109.91557 , 106.02945 , 109.235535,
        92.82604 ,  97.715744, 111.07597 ,  97.26159 , 101.34555 ,
       100.89409 , 101.71004 ,  93.459526, 101.22158 ,  86.590256,
       106.160385,  91.45002 ,  93.231926, 100.97634 , 111.19724 ,
       114.01759 , 112.47743 , 105.55773 , 103.26785 , 104.6653  ,
        92.79589 ,  96.06008 ,  80.86016 ,  92.711426,  91.27853 ,
        89.08174 , 109.973145, 111.05896 , 112.47437 ,  95.246185,
        96.23733 ,  95.49396 ,  92.56924 , 105.77985 ,  97.69933 ,
        92.87229 , 100.22215 , 105.31243 ,  97.39106 , 113.637566,
        97.40268 ,  96.31465 ,  93.41784 ,  95.48264 ,  95.963615,
       107.28592 , 102.83812 , 115.125084, 108.54558 ,  94.287285,
        94.0463  ,  99.6511  , 111.200966,  99.604256,  95.98065 ,
       101.35001 ,  93.090004, 102.23291 , 102.81947 ,  98.02277 ,
        94.48879 , 100.953545, 107.79157 , 107.517006, 107.7976  ,
       110.03068 ,  75.55683 ,  99.3241  , 100.34224 ,  90.81932 ,
        96.1512  ,  94.627426,  98.486855, 100.320175,  91.59918 ,
        93.254715,  91.11295 ,  93.404106,  93.46087 , 121.56308 ,
       109.457214, 108.03838 , 105.99564 ,  97.033424,  93.2079  ,
       116.19965 , 103.54547 , 109.71269 , 102.578835,  93.49053 ,
       104.64521 , 101.876495,  98.98937 , 101.32796 ,  95.02259 ,
        79.66337 , 104.793274,  96.37788 , 109.34374 ,  93.090004,
        91.655685,  95.55238 , 106.23665 , 100.06141 ,  87.19672 ,
       102.48274 , 110.5872  ,  77.9842  , 112.447624,  92.111176,
       111.089874,  89.4815  , 108.88189 ,  94.2992  , 105.35558 ,
       103.58807 ,  91.35499 , 101.245026,  95.165886,  93.93818 ,
        91.52335 , 108.000755,  96.70513 ,  78.324135,  92.03025 ,
        92.46536 ,  96.59836 , 114.63038 ,  92.56147 ,  90.95065 ,
       100.31079 ,  99.822235,  97.40926 ,  79.20304 ,  93.62026 ,
       111.977806, 101.95776 ,  89.2477  ,  94.25968 ,  93.27279 ,
       102.61146 ,  98.05278 ,  97.125206, 105.9482  ,  97.69184 ,
        99.7354  ,  89.027794, 102.888054, 110.34248 ,  93.92492 ,
       119.701225,  97.13945 , 115.99967 ,  97.32633 , 106.66469 ,
       106.9878  ,  95.486404,  94.42411 , 109.096954, 115.125084,
        97.85213 , 117.89285 ,  90.82614 , 108.06783 ,  96.6925  ,
       103.65946 ,  95.719505,  96.27929 , 104.08402 , 106.05026 ,
       107.82706 ,  95.508865, 101.758026, 108.08135 ,  91.167274,
        96.194496, 104.726006,  96.42779 ,  93.683586,  98.3057  ,
        93.2294  , 111.4832  ,  92.43657 ,  92.046165, 119.80203 ,
        99.82603 ,  90.00441 , 106.32813 ,  95.7515  , 105.45067 ,
        98.16382 , 101.731224, 101.41208 , 106.22128 , 105.549126,
        98.02277 , 111.36036 ,  92.1657  , 108.363686, 113.64714 ,
       110.12241 ,  93.56112 , 109.69749 , 103.281235,  93.44632 ,
       108.50755 , 114.54126 , 111.59792 , 107.89413 ,  99.503914,
       113.11079 ,  87.809715, 100.09023 ,  92.275055, 104.22723 ,
       113.43923 ,  95.21703 ,  91.30024 , 107.497055,  96.77325 ,
       100.599014,  99.369316, 114.70793 , 101.80139 ,  94.627426,
        99.287155,  90.27927 , 112.737175,  93.156975, 109.562935,
        92.86603 , 108.84201 , 105.95456 ,  95.93739 , 103.456474,
       100.5832  ,  92.02493 ,  92.635124,  79.6121  ,  96.1453  ,
       113.00833 ,  93.28063 ,  90.0457  ,  93.54978 , 108.14888 ,
        97.46726 ,  93.55177 ,  91.581665,  95.17035 , 103.39164 ,
        97.410866, 110.017166,  96.300735, 108.16073 , 119.54749 ,
        96.78028 , 107.14068 , 100.444786,  95.77234 ,  93.940475,
       100.228264,  91.75229 , 110.10403 ,  97.355286,  95.66925 ,
       113.750984,  99.87533 , 113.40694 , 101.91438 ,  96.015   ,
       115.10114 ,  94.36054 ,  97.13484 ,  93.31348 ,  84.05611 ,
       109.26471 ,  90.89559 ,  93.233864, 108.96346 , 107.38931 ,
        92.046745, 107.4663  ,  83.96288 , 112.26898 , 117.35675 ,
        93.699066, 112.05672 ,  98.7272  ,  88.182816, 104.41907 ,
        93.87859 , 109.52913 , 109.22071 , 103.15326 , 106.16786 ,
        91.43424 ,  96.84512 ,  93.62026 , 104.82871 , 101.89969 ,
        97.78906 ,  98.17559 , 108.82713 ,  96.84513 , 103.99316 ,
        96.36802 , 116.85271 ,  96.632996,  92.90041 , 109.131165,
        98.34534 , 114.03201 ,  90.61734 ,  84.03509 ,  99.0071  ,
       120.77556 , 110.00035 ,  92.381584,  94.20683 , 104.208046,
        92.1836  ,  95.22483 , 106.59468 , 112.34236 , 110.64063 ,
        96.7534  , 109.32598 ,  99.0644  ,  95.387566,  93.427536,
        90.88551 , 109.509865, 101.32796 ,  94.03197 , 116.54585 ,
        98.94524 , 105.34801 ,  95.18163 ,  81.11899 ,  94.179276,
       111.173515,  91.26577 , 113.910385, 115.386246, 107.36181 ,
       108.582924,  95.685776,  91.80598 ,  94.054375,  93.11122 ,
        97.61792 ,  95.54112 ,  92.87346 ,  97.00762 ,  93.12975 ,
       105.80267 , 108.9407  ,  98.443306, 105.42061 ,  91.95774 ,
       112.58301 , 105.04124 , 107.879135,  95.05396 ,  91.535995,
        97.64298 , 100.297844, 101.645485,  98.80256 ,  77.29312 ,
        96.23733 ,  90.18566 , 107.96181 ,  77.95072 ,  89.50897 ,
       108.40143 ,  88.60466 ,  74.42355 ,  94.82646 , 107.93278 ,
        91.6683  , 105.81932 , 104.51133 ,  83.32563 ,  81.51879 ,
        78.65797 , 103.171745, 107.46545 , 106.96706 , 112.1336  ,
       102.621994,  99.223175, 102.135994, 108.10208 ,  94.34622 ,
        97.261566, 108.03089 , 102.07669 ,  87.8684  , 105.889946,
       111.50042 , 107.34692 ,  94.44238 ,  97.58749 , 106.90057 ,
        94.23513 , 106.561424,  90.40647 ,  91.37398 ,  88.25339 ,
        90.9886  ,  96.64849 , 106.87288 , 114.54126 , 103.82931 ,
       108.846954, 100.23254 , 110.5872  , 102.10755 , 109.85729 ,
       108.4205  , 102.44129 , 101.054825, 112.58301 , 110.31834 ,
       113.129395, 101.74263 ,  92.84271 ,  95.48126 , 109.406784,
        98.73526 , 106.39422 , 114.265   , 101.29545 ,  97.151985,
       104.890526, 102.62304 , 109.71034 , 114.92729 , 110.94934 ,
       113.69058 , 104.98067 ,  95.3014  ,  92.74971 ,  96.27907 ,
        93.30806 ,  96.54071 , 107.97284 , 100.31945 ,  76.02857 ,
       116.43777 , 112.06929 , 114.92729 ,  90.37921 ,  97.04598 ,
        94.15455 ,  79.57401 ,  92.20731 ,  99.47629 , 111.2633  ,
        99.74899 ,  95.56461 , 108.461266,  99.760414,  97.910164,
        94.93058 ,  93.72932 , 103.085686, 113.43923 ,  95.83605 ,
        96.01889 , 117.191315, 101.29545 ,  97.81024 , 102.96418 ,
        99.5809  ,  96.15574 ,  76.16829 ,  79.519226, 110.92018 ,
       101.50278 , 109.25847 ,  94.38498 , 113.88445 , 108.38346 ,
       108.81171 ,  93.20263 ,  93.730034, 110.69118 , 106.23665 ,
        76.581535, 112.26807 ,  97.761154,  95.286736, 105.700356,
        77.293   , 105.3846  , 100.004906,  96.15767 , 103.11089 ,
       108.055855,  91.27853 ,  99.39003 ,  91.90958 , 109.89399 ,
       104.547935, 116.98362 ,  94.10133 , 106.062386, 108.08885 ,
       102.582146,  88.680565,  90.83284 , 101.58089 , 121.41821 ,
       114.817665, 110.85063 , 103.89663 ,  98.42852 ,  95.098   ,
        88.671005,  92.02493 , 114.53696 , 110.01976 , 108.93583 ,
        95.96474 ,  96.02881 ,  92.251526, 108.76701 , 125.89629 ,
       117.97771 , 109.19976 , 110.246895,  93.52081 ,  97.56037 ,
       111.2633  ,  96.09807 , 101.29545 , 106.934715,  95.28693 ,
        92.19081 , 109.27727 ,  93.13511 ,  92.606895,  78.05903 ,
        92.6704  ,  76.016136, 109.79392 , 108.8903  ,  93.78906 ,
       105.19317 , 107.453995,  93.62328 , 108.89701 , 106.47167 ,
        97.42113 ,  90.40816 ,  91.843994,  95.768074,  99.34241 ,
       109.30088 ,  94.78468 ,  92.86851 ,  91.40888 ,  95.06514 ,
       100.07215 , 112.36385 ,  89.5893  , 100.859436, 110.770744,
        98.543304,  99.3477  , 104.416695, 107.580444, 110.85865 ,
        95.77071 ,  93.231285, 100.72212 , 106.46493 ,  98.62514 ,
       116.01097 , 111.72348 ,  97.79918 , 103.15002 ,  91.947044,
        75.34031 , 100.91969 , 105.003494,  97.078255, 108.5825  ,
        92.83188 , 116.87806 , 104.422516, 119.08545 ,  90.77157 ,
       101.62801 , 101.30632 , 110.94815 ,  90.842255,  79.79945 ,
       106.06409 ,  92.28784 ,  95.91128 ,  99.08248 , 104.57547 ,
       103.171745, 100.831375], dtype=float32)

In [143]:
from sklearn.metrics import r2_score,mean_squared_error

In [144]:
print("Train acc:",xgb.score(xtrain_pca,ytrain))
print("Test acc:",xgb.score(xtest_pca,ytest))

Train acc: 0.8683846848224658
Test acc: 0.32854589571571746

In [145]:
r2_score(ytest,y_pred)

0.32854589571571746

In [146]:
np.sqrt(mean_squared_error(ytest,y_pred))

10.473005580922209

In [147]:
#predicting the test dataset values
testdf_pca=pca.transform(test_df)

In [148]:
testdf_pca.shape

(4209, 5)

In [149]:
target_test=xgb.predict(testdf_pca)
target_test

array([ 72.53579 ,  99.82208 ,  94.2005  , ...,  95.73133 , 106.609215,
        94.21588 ], dtype=float32)

In [150]:
print("Test acc:",xgb.score(testdf_pca,target_test))

Test acc: 1.0